version: "3.9"
services:
  db:
    image: "mysql:8.0.27"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: second_hand_site_checker
    networks:
      - second-hand-site-checker

networks:
  second-hand-site-checker:
    driver: bridge
    name: second-hand-site-checker